### ISSUE TITLE
Email notification

### ISSUE THREAD

**Issue by goeblj** [SAP/cloud-s4-sdk-pipeline#14]
Hi,

I configured sendNotifications as post build action in pipeline_config.yml for all branches.
I can send test emails from Jenkins.
If a build fails, email notification will not be send.
We use SDK version 1.7.1 and the last Jenkins image.

Regards
Jürgen

**Comment by jjtang1985** [comment]
Hi Jürgen,

thank you so much for reporting the issue.

Could you please show us the _postActions_ section of your _pipeline_config.yml_?

Best regards,

Junjie

**Comment by goeblj** [comment]
Hi Junjie,

here my configuration.

  postActions:
    enabled: true
    skipFeatureBranches: false
    recipients:
      - emailaddress

Regards
Jürgen

**Comment by jjtang1985** [comment]
I think the `sendNotification` attribute is missing in your config as well as in the documentation.

Please try the config below and let me know whether it works for you.

```
postActions:
  sendNotification:
    enabled: true
    skipFeatureBranches: false
    recipients:
      - emailaddress
```

Thank you.
