### ISSUE TITLE
fortify scan is not triggered

### ISSUE THREAD

**Issue by T1mey** [SAP/cloud-s4-sdk-pipeline#31]
We configured the execution of a fortify scan in the pipeline config.

```
steps:

 ...    
  executeFortifyScan:
    dockerImage: 'my.repo:version'
    fortifyCredentialId: 'FORTIFY_CREDENTIALS'

### Stage-specific configuration
stages:

  fortifyScan:
    sscUrl: 'https://test.ssc/ssc'
    fortifyCredentialId: 'FORTIFY_CREDENTIALS'
    fortifyProjectName: 'MyApp'
    projectVersionId: 'MyVersion'
```

But all 3rd party checks (incl. Fortify Scan) are skipped.

```
Stage "Third-party Checks" skipped due to when conditional
[Pipeline] parallel
[Pipeline] { (Branch: Checkmarx Scan)
[Pipeline] { (Branch: WhiteSource Scan)
[Pipeline] { (Branch: SourceClear Scan)
[Pipeline] { (Branch: Fortify Scan)
[Pipeline] { (Branch: Additional Tools)
[Pipeline] { (Branch: SonarQube Scan)
[Pipeline] stage
[Pipeline] { (Checkmarx Scan)
[Pipeline] stage
[Pipeline] { (WhiteSource Scan)
[Pipeline] stage
[Pipeline] { (SourceClear Scan)
[Pipeline] stage
[Pipeline] { (Fortify Scan)
[Pipeline] stage
[Pipeline] { (Additional Tools)
[Pipeline] stage
[Pipeline] { (SonarQube Scan)
Stage "Checkmarx Scan" skipped due to when conditional
[Pipeline] }
Stage "WhiteSource Scan" skipped due to when conditional
[Pipeline] }
Stage "SourceClear Scan" skipped due to when conditional
[Pipeline] }
Stage "Fortify Scan" skipped due to when conditional
[Pipeline] }
Stage "Additional Tools" skipped due to when conditional
[Pipeline] }
Stage "SonarQube Scan" skipped due to when conditional
```
